spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://newsto.cdu48eyauqk4.ap-northeast-2.rds.amazonaws.com:3306/newsTo?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: admin
    password: newsTo123

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      fail-on-empty-beans: false
