spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kongtteok?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: mdmstj2395!

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true