name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 13.125.46.77
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/app/newsTo"

      - name: Restart EC2 App
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 13.125.46.77
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'java' || true
            nohup java -jar /home/ubuntu/app/newsTo/*.jar > /home/ubuntu/app/newsTo/nohup.out 2>&1 &
